package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.ProjectReportTab
import jetbrains.buildServer.configs.kotlin.projectFeatures.projectReportTab
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<ProjectReportTab> {
            projectReportTab {
                id = "PROJECT_EXT_4"
                title = "Allure Report"
                startPage = "allure-report/index.html"
                buildType = "JavaAndTeamcity_Build"
                sourceBuildRule = ProjectReportTab.SourceBuildRule.LAST_SUCCESSFUL
            }
        }
        feature1.apply {
            sourceBuildRule = ProjectReportTab.SourceBuildRule.LAST_FINISHED
        }
    }
}
